### ISSUE TITLE
don't work on large file 

### ISSUE THREAD

**Issue by zendoonix** [x0a/thumbdata3-viewer#1]
Dear Admin 

i can't open large file ( about 3.5 GB ) with local and online , get AW,Snap ! on browser . 
please advise me 

thanks,

**Comment by x0a** [comment]
Thanks for your bug report. I made some updates in https://github.com/x0a/thumbdata3-viewer/commit/78757300a2d5f10c9aae03db663fb2b7a028960e to improve the handling of large files. Specifically, processing the file as individual chunks rather than loading the entire buffer into memory to prevent OOM conditions.

See if this fixed your problem. Keep in mind, thumbdata3 files are mostly empty. Sometimes a 2gb file only has about 20 thumbnails.

**Comment by zendoonix** [comment]
Thanks a lot for your kind attention and help to solve this issue . it's working 
Amirhosein
