### ISSUE TITLE
Not Working with Firefox in Windows 10 offiline

### ISSUE THREAD

**Issue by stevanuscolonne** [x0a/thumbdata3-viewer#3]
After selecting the thumbdata file nothing happen, only keep parsing
![keep parsing](https://user-images.githubusercontent.com/24591481/61863943-bd26bb80-aefa-11e9-8b06-e21d56eabd55.png)
Also happen when connected to internet.

It only works when using https://x0a.github.io/thumbdata3-viewer/

**Comment by x0a** [comment]
Hey,

The problem is that in order to be able to effectively parse large files (>3gb), I had to use web workers for best use of resources. Chrome and Firefox do not allow web workers to be executed from file:/// urls. In order to execute locally, you have to serve the files from an HTTP server.

If you have python3, you can use its built in HTTP server with ```python -m SimpleHTTPServer 8000``` from the ./dist directory, or ```npx serve``` if you have node.

Later on I might refactor things in order to only use web workers if possible.

**Comment by x0a** [comment]
I've pushed an update, feel free to try the new version. 

It might feel a little more sluggish than the "online" version because its unable to take advantage of web workers, but it should work.

[Edit] Nevermind. Seems the changes are only working for Chrome and not FF.

**Comment by x0a** [comment]
Seems Firefox was refusing to load the webworker on file: protocol but instead of throwing an error, it just failed silently. Solution is to manually throw an error when under file: protocol. 

Try it and feel free to reopen the issue if you have any more problems.
